user = CreateAdminService.new.call
puts 'CREATED ADMIN USER: ' << user.email

User.create!([
  {email: "cgarcia123@gmail.com", password: "password123", password_confirmation: "password123" , first_name: "Charlie", last_name: "Garcia", website: "http://www.cgracia.com",twitter: "http://twitter.com/thegarcia", field: "Ruby", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor laoreet sem vel dapibus. Pellentesque pretium libero dictum ipsum tincidunt.", role: 0},
  {email: "mlane123@gmail.com",password: "password123", password_confirmation: "password123" ,  first_name: "Mike", last_name: "Lane", website: "http://www.michaelane.com", twitter: "http://twitter.com/mlane", field: "Python", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor laoreet sem vel dapibus. Pellentesque pretium libero dictum ipsum tincidunt.", role: 0},
  {email: "acheekz@gmail.com", password: "password123", password_confirmation: "password123" ,  first_name: "AL", last_name: "Cheekz", website: "http://www.alcheekz.com", twitter: "http://twitter.com/alcheekz_ftw", field: "C++", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor laoreet sem vel dapibus. Pellentesque pretium libero dictum ipsum tincidunt.", role: 0},
  {email: "cbennet@gmail.com",password: "password123", password_confirmation: "password123" , first_name: "Chance", last_name: "Bennet", website: "http://www.chanceraps.com", twitter: "http://twitter.com/chancetherapper", field: "PHP", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor laoreet sem vel dapibus. Pellentesque pretium libero dictum ipsum tincidunt.", role: 0},
  {email: "kwest@gmail.com", password: "password123", password_confirmation: "password123" , first_name: "Kanye", last_name: "West", website: "http://www.kanye.com", twitter: "http://twitter.com/kanye", field: "HTML/CSS", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor laoreet sem vel dapibus. Pellentesque pretium libero dictum ipsum tincidunt.", role: 0},
  {email: "bobama@gmail.com", password: "password123", password_confirmation: "password123" , first_name: "Barack", last_name: "Obama", website: "http://www.barackobama.com", twitter: "http://twitter.com/barackobama",field: "Javascript", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor laoreet sem vel dapibus. Pellentesque pretium libero dictum ipsum tincidunt.", role: 0},
  {email: "jayz@gmail.com", password: "password123", password_confirmation: "password123" , first_name: "Jay", last_name: "Z", website: "http://www.jayz.com",twitter: "http://twitter.com/s_c_", field: "C++", bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porttitor laoreet sem vel dapibus. Pellentesque pretium libero dictum ipsum tincidunt.", role: 0}
])
